tlens_model_name: pythia-14m
tlens_config: null
saes:
  dict_size_to_input_ratio: 2.0
  sae_position_name: hook_resid_post
train:
  seed: 0
  num_epochs: 2
  batch_size: 8
  effective_batch_size: 128
  lr: 1e-3
  act_sparsity_lambda: 0.001
  sparsity_p_norm: 0.7
  warmup_steps: 0
  max_grad_norm: 1.0
  loss_include_sae_inp_orig: False
  loss_include_sae_out_orig: False
  loss_include_sae_inp_sae_out: False
  loss_include_sae_sparsity: False
wandb:
  project: sparsify
  entity: lee
