seed: 0
saved_model_dir: /path/to/saved_model_dir
train:
  learning_rate: 0.001
  batch_size: 1024
  n_epochs: 8
  type_of_sparsifier: sae
  sparsity_lambda: 0.005
  dict_eles_to_input_ratio: 10.0
  sparsifier_in_out_recon_loss_scale: 0.0
  k: 128
wandb_project: mlp-mnist-sae
