seed: 0
model:
  hidden_sizes:
    - 100
    - 100
train:
  learning_rate: 0.001
  batch_size: 1024
  epochs: 50
  save_dir: sparsify/models
  model_name: orig-train-lr-0.001_bs-1024-[100, 100]_2024-01-14_18-00-27
  sparsity_lambda: 50.0
  save_every_n_epochs: null
wandb:
  project: mlp-mnist-sae
  entity: lee_sharkey
