tlens_model_name: null
tlens_config:
  d_model: 16
  n_layers: 2
  n_ctx: 128
  d_head: 4
  d_vocab: 10
  act_fn: gelu
  dtype: float32
input_size: 768
n_dict_components: 10
sae_orig: true
sae_sparsity: true
train:
  batch_size: 3
  lr: 1e-3
