wandb_project: gpt2-layerwise
wandb_run_name: null
wandb_run_name_prefix: "ctx128_seed1"

seed: 0
tlens_model_name: gpt2-small
tlens_model_path: null

n_samples: 800_000
save_every_n_samples: null
eval_every_n_samples: 40_000
eval_n_samples: 2000
log_every_n_grad_steps: 20
collect_act_frequency_every_n_samples: 10_000
act_frequency_n_tokens: 500_000  #500k tokens is ~977 samples
batch_size: 80
effective_batch_size: 160
lr: 0.05
adam_beta1: 0.9  # pytorch defaults to 0.9
lr_schedule: cosine
min_lr_factor: 0.1
warmup_samples: 20_000
max_grad_norm: 1.0

loss:
  sparsity:
    p_norm: 1.0
    coeff: 0.1
  in_to_orig: null
  out_to_orig: null
  out_to_in:
    coeff: 1.0
  logits_kl: null
train_data:
  dataset_name: apollo-research/Skylion007-openwebtext-tokenizer-gpt2
  is_tokenized: true
  tokenizer_name: gpt2
  streaming: true
  split: train
  n_ctx: 1024
  seed: 0
eval_data:
  dataset_name: apollo-research/Skylion007-openwebtext-tokenizer-gpt2
  is_tokenized: true
  tokenizer_name: gpt2
  streaming: true
  split: train
  n_ctx: 1024
  seed: 1
saes:
  retrain_saes: false
  pretrained_sae_paths: null
  sae_positions:
    - blocks.1.hook_resid_post
  dict_size_to_input_ratio: 32.0