seed: 0
tlens_model_name: gpt2-small
tlens_model_path: null
train:
  n_samples: 2000
  batch_size: 8
  effective_batch_size: 128
  lr: 1e-3
  warmup_samples: 0
  max_grad_norm: 1.0
  loss_configs:
    sparsity:
      p_norm: 0.5
      coeff: 0.001
    inp_to_orig:
      coeff: 1.0
    out_to_orig:
      coeff: 1.0
    inp_to_out: null
    logits_kl:
      coeff: 1.0
    normalize_mse: True
data:
  dataset_name: apollo-research/sae-Skylion007-openwebtext-tokenizer-gpt2
  is_tokenized: true
  tokenizer_name: gpt2
  streaming: true
  split: train
  n_ctx: 1024
saes:
  sae_position_names: hook_resid_post
wandb_project: gpt2-small-owt