seed: 0
tlens_model_name: pythia-14m
tlens_model_path: null
train:
  n_samples: 1000
  n_epochs: 2
  batch_size: 8
  effective_batch_size: 128
  lr: 1e-3
  warmup_steps: 0
  max_grad_norm: 1.0
  loss_configs:
    sparsity:
      p_norm: 0.7
      coeff: 0.001
    inp_to_orig:
      coeff: 1.0
    out_to_orig:
      coeff: 1.0
    inp_to_out: null
    logits:
      coeff: 1.0
data:
  dataset_name: apollo-research/sae-Skylion007-openwebtext-tokenizer-EleutherAI-gpt-neox-20b
  is_tokenized: true
  tokenizer_name: EleutherAI/gpt-neox-20B
  streaming: true
  split: train
saes:
  sae_position_name: hook_resid_post
wandb_project: null

