seed: 0
tlens_model_name: null
tlens_model_path: sparsify/scripts/train_tlens/out/tiny-gpt2_lr-0.001_bs-16_2024-02-05_12-28-22
train:
  n_epochs: 2
  batch_size: 3
  lr: 1e-3
  loss_include_sae_inp_orig: true
  loss_include_sae_out_orig: true
saes:
  sae_position_name: hook_resid_post
tokenizer_name: gpt2
wandb_project: sparsify-custom
