seed: 0
tlens_model_name: null
tlens_model_path: sparsify/scripts/train_tlens/out/tiny-gpt2_lr-0.001_bs-16_2024-02-05_12-28-22
train:
  batch_size: 3
  lr: 1e-3
  loss:
    sparsity:
      p_norm: 0.5
      coeff: 0.001
    inp_to_orig:
      coeff: 1.0
    out_to_orig:
      coeff: 1.0
    inp_to_out: null
    logits_kl:
      coeff: 1.0
data:
  dataset_name: apollo-research/Skylion007-openwebtext-tokenizer-gpt2
  is_tokenized: true
  tokenizer_name: gpt2
  streaming: true
  split: train
  n_ctx: 1024
saes:
  sae_position_names: hook_resid_post
wandb_project: custom
