seed: 0
tlens_model_name: roneneldan/TinyStories-1M
tlens_model_path: null
train:
  save_every_n_samples: null
  n_samples: 40000
  batch_size: 18
  effective_batch_size: 18
  lr: 1e-3
  warmup_steps: 0
  max_grad_norm: 1.0
  loss_configs:
    sparsity:
      p_norm: 0.7
      coeff: 0.00005
    inp_to_orig: null
    out_to_orig:
      coeff: 1.0
    inp_to_out: null
    logits: null
data:
  dataset_name: apollo-research/sae-roneneldan-TinyStories-tokenizer-gpt2
  is_tokenized: true
  tokenizer_name: gpt2
  streaming: true
  split: train
  n_ctx: 512
saes:
  sae_position_name: blocks.3.hook_resid_post
  dict_size_to_input_ratio: 1.0
wandb_project: tinystories-1m

