seed: 0
tlens_model_name: roneneldan/TinyStories-1M
tlens_model_path: null
train:
  save_every_n_samples: null
  n_samples: 200000  # 918604 samples of 512 tokens
  log_every_n_steps: 20
  collect_discrete_metrics_every_n_samples: 10000
  discrete_metrics_n_tokens: 500_000  #500k tokens is ~977 samples
  log_ce_loss: true
  batch_size: 10
  effective_batch_size: 10
  lr: 5e-3
  warmup_steps: 500
  max_grad_norm: 1.0
  interpolate_n_steps: 500
  loss_configs:
    sparsity:
      p_norm: 0.6
      coeff: 5e-6
    inp_to_orig: null
    out_to_orig: null
    inp_to_out: null
    logits_kl:
      coeff: 1.0
data:
  dataset_name: apollo-research/sae-roneneldan-TinyStories-tokenizer-gpt2
  is_tokenized: true
  tokenizer_name: gpt2
  streaming: true
  split: train
  n_ctx: 512
saes:
  sae_position_names: hook_resid_post
  dict_size_to_input_ratio: 10.0
wandb_project: tinystories-1m-interpolate-play

