seed: 0
tlens_model_name: tiny-stories-1M
tlens_model_path: null
train:
  layer_wise: False
  n_epochs: 2
  batch_size: 8
  effective_batch_size: 128
  lr: 1e-3
  warmup_steps: 0
  max_grad_norm: 1.0
  loss_configs:
    sparsity:
      p_norm: 0.7
      coeff: 0.001
    inp_to_orig:
      coeff: 1.0
    out_to_orig:
      coeff: 1.0
    inp_to_out: null
    logits:
      coeff: 1.0
saes:
  sae_position_names: hook_resid_post
wandb_project: sparsify-tiny-stories-1M