name: Checks

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - 'README.md'
      - 'ACCESS.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - 'README.md'
      - 'ACCESS.md'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]"
    - name: Check with Black
      run: |
        black --check --diff --line-length 100 mypkg scripts tests
    - name: Check with isort
      run: |
        isort --check --thirdparty wandb --profile black mypkg scripts tests
    - name: Check with mypy
      run: |
        mypy --ignore-missing-imports mypkg scripts
    - name: Run tests
      run: |
        pytest tests